source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in ruby-rspec.gemspec
# gemspec

gem 'nokogiri'
gem 'rack', '~> 2.0.1'
gem 'rspec'